{% set version = "0.1.7.post2" %}
{% set lib_ver = version.split(".")[:3] | join(".") %}

package:
  name: qdldl-python
  version: {{ version }}

source:
  url: https://github.com/osqp/qdldl-python/archive/refs/tags/v.{{ version }}.tar.gz
  sha256: fa3294d5be792df52e53aaa4373c37f36f66661a86b8629bda8691b39245dcb5
  patches:
    - patches/0001-use-Ninja-everywhere.patch
    - patches/0002-build-against-conda-forge-s-libqdldl.patch
    - patches/0003-build-qdldlamd-as-shared-lib-and-install-it.patch
    - patches/0004-Do-not-pass-CMAKE_GENERATOR-as-variable.patch

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - python
    - pip
    - libqdldl ={{ lib_ver }}
    - numpy
    - pybind11
  run:
    - python
    - scipy

test:
  requires:
    - pytest
  imports:
    - qdldl
  # Disabled tests due to issues in QEMU, see https://github.com/scipy/scipy/issues/14560
  source_files:   # [not ppc64le]
    - tests/        # [not ppc64le]
  commands:   # [not ppc64le]
    - pytest tests  # [not ppc64le]

about:
  home: https://github.com/oxfordcontrol/qdldl-python
  license: Apache-2.0
  license_file: LICENSE
  summary: Python interface to the QDLDL free LDL factorization routine for quasi-definite linear systems

  description: |
    Python interface to the [QDLDL](https://github.com/oxfordcontrol/qdldl/) free
    LDL factorization routine for quasi-definite linear systems: `Ax = b`.
  dev_url: https://github.com/oxfordcontrol/qdldl-python

extra:
  recipe-maintainers:
    - adament
    - bstellato
    - gbanjac
    - h-vetinari
